import json

DOMAIN_EXAMPLES = {
    "security": [
        "CVE-2024-3094 xz utils",
        "recent openssh vulnerability",
        "log4j exploit mitigation",
        "CISA advisory for Ivanti",
        "GitHub security advisory GHSA-xxxx",
        "NVD severity for latest curl CVE",
    ],
    "vendor-status": [
        "GitHub Actions runner outage",
        "is AWS us-east-1 down",
        "cloudflare degraded status today",
        "Slack status page incident",
        "OpenAI API status",
        "Vercel outage right now",
    ],
    "package-registry": [
        "npm install lodash",
        "PyPI requests package",
        "cargo add serde",
        "maven org.springframework package",
        "composer require guzzlehttp/guzzle",
        "docker pull ubuntu",
    ],
    "github": [
        "GitHub pull request 123 on react",
        "issue 54 on facebook/react",
        "Vercel next.js discussions",
        "GitHub repo torvalds/linux",
        "TensorFlow GitHub commits",
        "search GitHub issues for bug",
    ],
    "changelog": [
        "React 19 release notes",
        "what is new in Python 3.12",
        "Next.js changelog version 14",
        "Docker Desktop release notes",
        "Kubernetes v1.30 changelog",
        "Postgres 16 version history",
    ],
    "papers": [
        "attention is all you need paper",
        "transformers arXiv 2017",
        "LLama 3 technical report",
        "DOI 10.1145/3357384.3357396",
        "PubMed latest research on mRNA",
        "scientific study on sleep and memory",
    ],
    "specs": [
        "RFC 2616 HTTP 1.1",
        "HTML5 W3C specification",
        "ECMAScript 2024 language spec",
        "WHATWG fetch standard",
        "JSON RFC 8259",
        "OpenAPI 3.1 specification",
    ],
    "forums": [
        "Stack Overflow how to exit vim",
        "Reddit r/programming",
        "Rust discourse generics thread",
        "Hacker News discussion on AI",
        "Swift forums actor isolation",
        "StackExchange physics quantum discussion",
    ],
    "legal": [
        "GDPR data retention compliance requirements",
        "official visa extension rules Germany",
        "software copyright fair use case law",
        "contract liability clause enforceability",
        "HIPAA regulation update",
        "EU trademark registration process",
    ],
    "medical": [
        "clinical guideline for asthma treatment",
        "drug dosage for amoxicillin official guidance",
        "PubMed migraine prevention study",
        "FDA warning for weight loss medication",
        "WHO guidance for dengue treatment",
        "contraindications for warfarin therapy",
    ],
    "finance": [
        "ETF allocation for retirement portfolio",
        "SEC filing for Tesla annual report",
        "IRS guidance for RSU taxation",
        "Federal Reserve interest rate decision",
        "consumer finance mortgage disclosure rules",
        "banking regulation capital requirements",
    ],
    "cloud-docs": [
        "AWS IAM role trust policy reference",
        "Azure Entra conditional access documentation",
        "Google Cloud Run service account docs",
        "Kubernetes deployment rollout strategy docs",
        "Terraform provider alias reference",
        "EKS load balancer controller docs",
    ],
    "ai-ml": [
        "OpenAI embeddings model card",
        "Anthropic tool use documentation",
        "Hugging Face transformers benchmark",
        "prompt engineering best practices for RAG",
        "Gemini function calling docs",
        "fine-tuning sentence transformer guide",
    ],
    "ecommerce": [
        "best laptop under 1000 official pricing",
        "Nike return policy official store",
        "iPhone 16 price and shipping",
        "compare vacuum cleaner product reviews",
        "coupon code and discount for running shoes",
        "official product page for DJI Mini",
    ],
    "trading": [
        "Nasdaq premarket trading hours today",
        "CME futures contract specs official",
        "short interest reporting rules FINRA",
        "options assignment risk official guidance",
        "NYSE holiday market calendar",
        "CFTC margin requirements for futures",
    ],
    "quantum": [
        "quantum error correction roadmap IBM Research",
        "qiskit surface code tutorial",
        "quantum benchmark for trapped-ion systems",
        "bosonic code practical roadmap",
        "qLDPC decoding research overview",
        "Google Quantum AI error correction update",
    ],
    "shopify": [
        "Shopify admin API webhook docs",
        "Shopify Liquid theme app extension guide",
        "Shopify checkout extensibility migration",
        "help.shopify.com order editing",
        "Shopify Plus B2B setup docs",
        "Shopify storefront API rate limits",
    ],
    "standards": [
        "WCAG 2.2 color contrast requirements",
        "NIST password guidelines latest",
        "ISO 27001 control mapping official",
        "PCI DSS 4.0 segmentation requirements",
        "OWASP ASVS authentication standard",
        "FedRAMP moderate baseline controls",
    ],
    "news-current-events": [
        "latest OpenAI announcement headlines",
        "breaking news on Nvidia earnings",
        "current election headlines France",
        "Reuters coverage of ECB rate decision",
        "latest sanctions news Russia",
        "official statement on major acquisition today",
    ],
    "local-howto": [
        "parking permit city hall appointment near me",
        "DMV vehicle registration office hours",
        "trash pickup schedule county official",
        "Bürgeramt Anmeldung appointment Berlin",
        "local public transport fare card official",
        "city business license application office",
    ],
    "web": [
        "how to boil an egg",
        "best movies of 2023",
        "history of the roman empire",
        "capital of France",
        "population of Tokyo",
        "how to tie a tie",
    ],
}

with open("data/router/gold-domain.jsonl", "w") as f:
    total = 0
    for label, queries in DOMAIN_EXAMPLES.items():
        for query in queries:
            row = {
                "query": query,
                "label": label,
                "rationale": f"Synthetic gold example for {label}",
                "inputText": query,
            }
            f.write(json.dumps(row) + "\n")
            total += 1

print(f"Generated {total} gold domain examples.")
